// Alertas
export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA'
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA'
// Warning
export const MOSTRAR_WARNING = 'MOSTRAR_WARNING'
export const OCULTAR_WARNING = 'OCULTAR_WARNING'
// Success
export const MOSTRAR_SUCCESS = 'MOSTRAR_SUCCESS'
export const OCULTAR_SUCCESS = 'OCULTAR_SUCCESS'

// Suertes
export const MOSTRAR_REGISTRO_SUERTE = 'MOSTRAR_REGISTRO_SUERTE'
export const OCULTAR_REGISTRO_SUERTE = 'OCULTAR_REGISTRO_SUERTE'


// Tablones
export const MOSTRAR_REGISTRO_TABLON = 'MOSTRAR_REGISTRO_TABLON'
export const OCULTAR_REGISTRO_TABLON = 'OCULTAR_REGISTRO_TABLON'



// Cortes
export const MOSTRAR_CORTES = 'MOSTRAR_CORTES'
export const OCULTAR_CORTES= 'OCULTAR_CORTES'

export const MOSTRAR_REGISTRO_CORTE = 'MOSTRAR_FORM_CORTE'
export const OCULTAR_REGISTRO_CORTE = 'OCULTAR_FORM_CORTE'


// Labores
export const MOSTRAR_LABORES = 'MOSTRAR_LABORES'
export const OCULTAR_LABORES = 'OCULTAR_LABORES'

export const MOSTRAR_REGISTRO_LABOR = 'MOSTRAR_REGISTRO_LABOR'
export const OCULTAR_REGISTRO_LABOR = 'OCULTAR_REGISTRO_LABOR'

// Herbicidas
export const MOSTRAR_HERBICIDAS = 'MOSTRAR_HERBICIDAS'
export const OCULTAR_HERBICIDAS = 'OCULTAR_HERBICIDAS'

export const MOSTRAR_REGISTRO_APLICACION_HERBICIDA = 'MOSTRAR_REGISTRO_APLICACION_HERBICIDA'
export const OCULTAR_REGISTRO_APLICACION_HERBICIDA = 'OCULTAR_REGISTRO_APLICACION_HERBICIDA'

export const MOSTRAR_REGISTRO_TRATAMIENTO_HERBICIDA = 'MOSTRAR_REGISTRO_TRATAMIENTO_HERBICIDA'
export const OCULTAR_REGISTRO_TRATAMIENTO_HERBICIDA = 'OCULTAR_REGISTRO_TRATAMIENTO_HERBICIDA'

// Fertilizantes
export const MOSTRAR_FERTILIZANTES = 'MOSTRAR_FERTILIZANTES'
export const OCULTAR_FERTILIZANTES = 'OCULTAR_FERTILIZANTES'

export const MOSTRAR_REGISTRO_APLICACION_FERTILIZANTE = 'MOSTRAR_REGISTRO_APLICACION_FERTILIZANTE'
export const OCULTAR_REGISTRO_APLICACION_FERTILIZANTE = 'OCULTAR_REGISTRO_APLICACION_FERTILIZANTE'

export const MOSTRAR_REGISTRO_TRATAMIENTO_FERTILIZANTE = 'MOSTRAR_REGISTRO_TRATAMIENTO_FERTILIZANTE'
export const OCULTAR_REGISTRO_TRATAMIENTO_FERTILIZANTE = 'OCULTAR_REGISTRO_TRATAMIENTO_FERTILIZANTE'

// Plagas
export const MOSTRAR_PLAGAS= 'MOSTRAR_PLAGAS'
export const OCULTAR_PLAGAS = 'OCULTAR_PLAGAS'

export const MOSTRAR_REGISTRO_PLAGA = 'MOSTRAR_REGISTRO_PLAGA'
export const OCULTAR_REGISTRO_PLAGA = 'OCULTAR_REGISTRO_PLAGA'

export const VER_PRODUCTOS = 'VER_PRODUCTOS'
export const OCULTAR_PRODUCTOS = 'OCULTAR_PRODUCTOS'

// Lluvias
export const MOSTRAR_LLUVIAS = 'MOSTRAR_LLUVIAS'
export const OCULTAR_LLUVIAS = 'OCULTAR_LLUVIAS'

export const MOSTRAR_REGISTRO_LLUVIA = 'MOSTRAR_REGISTRO_LLUVIA'
export const OCULTAR_REGISTRO_LLUVIA = 'OCULTAR_REGISTRO_LLUVIA'

// Cosechas
export const MOSTRAR_COSECHAS = 'MOSTRAR_COSECHAS'
export const OCULTAR_COSECHAS = 'OCULTAR_COSECHAS'

export const MOSTRAR_REGISTRO_COSECHA = 'MOSTRAR_REGISTRO_COSECHA'
export const OCULTAR_REGISTRO_COSECHA = 'OCULTAR_REGISTRO_COSECHA'


// Prontuario
export const SELECCIONAR_SUERTE = 'SELECCIONAR_SUERTE'
export const SELECCIONAR_FECHA_INICIAL = 'SELECCIONAR_FECHA_INICIAL'
export const SELECCIONAR_FECHA_FINAL = 'SELECCIONAR_FECHA_FINAL'


// SUERTES PARA LOS PLUVIOMETROS
export const SELECCIONAR_SUERTES = 'SELECCIONAR_SUERTES'

// Suertes
//export const AGREGAR_SUERTE = 'AGREGAR_SUERTE'
//export const AGREGAR_SUERTE_EXITO = 'AGREGAR_SUERTE_EXITO'
//export const AGREGAR_SUERTE_ERROR = 'AGREGAR_SUERTE_ERROR'

//export const COMENZAR_DESCARGA_SUERTES = 'COMENZAR_DESCARGA_SUERTES'
//export const DESCARGA_SUERTES_EXITO = 'DESCARGA_SUERTES_EXITO'
//export const DESCARGA_SUERTES_ERROR = 'DESCARGA_SUERTES_ERROR'

//export const OBTENER_SUERTE_VER = 'OBTENER_SUERTE_VER'
//export const SUERTE_VER_EXITO = 'SUERTE_VER_EXITO'
//export const SUERTE_VER_ERROR = 'SUERTE_VER_ERROR'


// export const AGREGAR_CORTE = 'AGREGAR_CORTE'
// export const AGREGAR_CORTE_EXITO = 'AGREGAR_CORTE_EXITO'
// export const AGREGAR_CORTE_ERROR = 'AGREGAR_CORTE_ERROR'
// export const OBTENER_CORTE_VER = 'OBTENER_CORTE_VER'
// export const OBTENER_CORTE_EDITAR = 'OBTENER_CORTE_EDITAR'
// export const COMENZAR_EDICION_CORTE = 'COMENZAR_EDICION_CORTE'
// export const CORTE_EDITADO_EXITO = 'CORTE_EDITADO_EXITO'
// export const CORTE_EDITADO_ERROR = 'CORTE_EDITADO_ERROR'
// export const CANCELAR_CORTE_EDITADO = 'CANCELAR_CORTE_EDITADO'


// Fecha de corte
// export const AGREGAR_FECHA_CORTE = 'AGREGAR_FECHA_CORTE'
// export const AGREGAR_FECHA_CORTE_EXITO = 'AGREGAR_FECHA_CORTE_EXITO'
// export const AGREGAR_FECHA_CORTE_ERROR = 'AGREGAR_FECHA_CORTE_ERROR'



// form







// Form Registro labores


// Form Registro herbicidas


// Form Registro fertilizantes


// Form Registro plagas


// Form Registro lluvias


// Form Registro cosechas


// Form Registro tablones
//export const MOSTRAR_FORM_REGISTRO_TABLON = 'MOSTRAR_FORM_REGISTRO_TABLON'
//export const OCULTAR_FORM_REGISTRO_TABLON = 'OCULTAR_FORM_REGISTRO_TABLON'

// Registrar Labores
// export const AGREGAR_LABOR = 'AGREGAR_LABOR'
// export const AGREGAR_LABOR_EXITO = 'AGREGAR_LABOR_EXITO'
// export const AGREGAR_LABOR_ERROR = 'AGREGAR_LABOR_ERROR'

// Registrar Herbicidad
// export const AGREGAR_APLICACION_HERBICIDA = 'AGREGAR_APLICACION_HERBICIDA'
// export const AGREGAR_APLICACION_HERBICIDA_EXITO = 'AGREGAR_APLICACION_HERBICIDA_EXITO'
// export const AGREGAR_APLICACION_HERBICIDA_ERROR = 'AGREGAR_APLICACION_HERBICIDA_ERROR'
// export const MOSTRAR_TRATAMIENTO_HERBICIDAS = 'MOSTRAR_TRATAMIENTO_HERBICIDAS'
// export const OCULTAR_TRATAMIENTO_HERBICIDAS = 'OCULTAR_TRATAMIENTO_HERBICIDAS'
// export const AGREGAR_TRATAMIENTO_HERBICIDA = 'AGREGAR_TRATAMIENTO_HERBICIDA'
// export const AGREGAR_TRATAMIENTO_HERBICIDA_EXITO = 'AGREGAR_TRATAMIENTO_HERBICIDA_EXITO'
// export const AGREGAR_TRATAMIENTO_HERBICIDA_ERROR = 'AGREGAR_TRATAMIENTO_HERBICIDA_ERROR'
// export const MOSTRAR = 'MOSTRAR'
// export const OCULTAR = 'OCULTAR'

// Registrar Fertilizantes
// export const AGREGAR_APLICACION_FERTILIZANTE = 'AGREGAR_APLICACION_FERTILIZANTE'
// export const AGREGAR_APLICACION_FERTILIZANTE_EXITO = 'AGREGAR_APLICACION_FERTILIZANTE_EXITO'
// export const AGREGAR_APLICACION_FERTILIZANTE_ERROR = 'AGREGAR_APLICACION_FERTILIZANTE_ERROR'
// export const MOSTRAR_TRATAMIENTO_FERTILIZANTES = 'MOSTRAR_TRATAMIENTO_FERTILIZANTES'
// export const OCULTAR_TRATAMIENTO_FERTILIZANTES = 'OCULTAR_TRATAMIENTO_FERTILIZANTES'
// export const AGREGAR_TRATAMIENTO_FERTILIZANTE = 'AGREGAR_TRATAMIENTO_FERTILIZANTE'
// export const AGREGAR_TRATAMIENTO_FERTILIZANTE_EXITO = 'AGREGAR_TRATAMIENTO_FERTILIZANTE_EXITO'
// export const AGREGAR_TRATAMIENTO_FERTILIZANTE_ERROR = 'AGREGAR_TRATAMIENTO_FERTILIZANTE_ERROR'
// export const MOSTRARF = 'MOSTRARF'
// export const OCULTARF = 'OCULTARF'

// Registrar Plagas
// export const AGREGAR_TRATAMIENTO_PLAGA = 'AGREGAR_TRATAMIENTO_PLAGA'
// export const AGREGAR_TRATAMIENTO_PLAGA_EXITO = 'AGREGAR_TRATAMIENTO_PLAGA_EXITO'
// export const AGREGAR_TRATAMIENTO_PLAGA_ERROR = 'AGREGAR_TRATAMIENTO_PLAGA_ERROR'


// Registrar Lluvia
// export const AGREGAR_LLUVIA = 'AGREGAR_LLUVIA'
// export const AGREGAR_LLUVIA_EXITO = 'AGREGAR_LLUVIA_EXITO'
// export const AGREGAR_LLUVIA_ERROR = 'AGREGAR_LLUVIA_ERROR'

// Registrar Cosecha
// export const AGREGAR_COSECHA = 'AGREGAR_COSECHA'
// export const AGREGAR_COSECHA_EXITO = 'AGREGAR_COSECHA_EXITO'
// export const AGREGAR_COSECHA_ERROR = 'AGREGAR_COSECHA_ERROR'
// export const OBTENER_COSECHA_EDITAR = 'OBTENER_COSECHA_EDITAR'
// export const COMENZAR_EDICION_COSECHA = 'COMENZAR_EDICION_COSECHA'
// export const COSECHA_EDITADO_EXITO = 'COSECHA_EDITADO_EXITO'
// export const COSECHA_EDITADO_ERROR = 'COSECHA_EDITADO_ERROR'
// export const CANCELAR_COSECHA_EDITADO = 'CANCELAR_COSECHA_EDITADO'

// Registrar tablon
// export const AGREGAR_TABLON = 'AGREGAR_TABLON'
// export const AGREGAR_TABLON_EXITO = 'AGREGAR_TABLON_EXITO'
// export const AGREGAR_TABLON_ERROR = 'AGREGAR_TABLON_ERROR'
